// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iegssgjjnktnwfpojmfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllZ3NzZ2pqbmt0bndmcG9qbWZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0ODAyNzIsImV4cCI6MjA3MjA1NjI3Mn0.rdDUjYrvaNyXKxh6Jo_DRAYPcf-n8bAxdhqlO6C19hE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});